name: MoreAirstrike
main: airstrike.Airstrike
version: 1.6
authors: [muCkk, zhuowei]
commands:
  as:
    description: bomb players with TNT, creepers, angry wolves, arrows, or splash potions.
    usage: |
             /<command> <tnt/cr/arrow/wolf/reverse/potion> <player> <amount> <height/potionvalue>
             <tnt/cr/arrow/wolf/reverse/potion> TNT, arrow, wolf, potion of poison, or Creeper? If no <amount> is given the default value is used.
             <height/potionvalue> is for TNT and potions only. 
  asset:
      description: Used to set up the config
      usage: |
              /<command> <key> <value>
permissions:
  airstrike.as.tnt:
    description: Allows the player to access /as tnt.

  airstrike.as.cr:
    description: Allows the player to access /as cr.

  airstrike.as.arrow:
    description: Allows the player to access /as arrow.

  airstrike.as.wolf:
    description: Allows the player to access /as wolf.

  airstrike.as.reverse:
    description: Allows the player to access /as reverse.

  airstrike.as.potion:
    description: Allows the player to access /as potion.

  airstrike.as:
    description: Allows the player to use all features of the /as command.
    default: op
    children:
      airstrike.as.tnt: true
      airstrike.as.cr: true
      airstrike.as.arrow: true
      airstrike.as.wolf: true
      airstrike.as.reverse: true
      airstrike.as.potion: true

  airstrike.asset:
    description: Allows the player to change Airstrike's config.
    default: op

